// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSUffkKY2f0lmqfevsASMtiiPyxaHw6_4',
    appId: '1:857783846160:android:c05b2f3054d28129c79195',
    messagingSenderId: '857783846160',
    projectId: 'ateam-f4dc7',
    storageBucket: 'ateam-f4dc7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMEKSUgqxzuspedHLQlz_zfBj6yw8FuXc',
    appId: '1:857783846160:ios:dba7e7a6b4173da5c79195',
    messagingSenderId: '857783846160',
    projectId: 'ateam-f4dc7',
    storageBucket: 'ateam-f4dc7.appspot.com',
    iosBundleId: 'com.example.at3am',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMEKSUgqxzuspedHLQlz_zfBj6yw8FuXc',
    appId: '1:857783846160:ios:a509a2a91c5e1df0c79195',
    messagingSenderId: '857783846160',
    projectId: 'ateam-f4dc7',
    storageBucket: 'ateam-f4dc7.appspot.com',
    iosBundleId: 'com.example.at3am.RunnerTests',
  );
}
